<?php if (Mage::getSingleton('customer/session')->isLoggedIn()) : ?>

    <div class="block block-poll" style="height: 250px;">
        <br>
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            

            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
                <?php
                $customer = Mage::getSingleton('customer/session')->getCustomer();
                $custID = $customer->getID();
                $model = Mage::getModel('uploader/uploader');
                $collection = $model->getCollection()
                        ->addFieldToFilter('user_id' , $custID)
                        ->getData();
                
                $isActive = True;
                
                foreach ($collection as $item) : ?>
                    <div class="item <?= ($isActive ? 'active' : ''); ?>">
                        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/rwd/default/images/carousel/<?php echo $item['name'];?>.<?php echo $item['ext'];?>"  alt="<?php echo $item['name'];?>" width="460" height="345">
                        <div class="carousel-caption"></div>
                    </div>     
                <?php
                    $isActive = false;
                    endforeach;
                ?>               
            </div>

            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
<?php endif; ?>
